Repository hardcodet/wpf-notifyicon, pull requests merged in 2019-07, with the labels that each got.

#1 Changed the version to a shields.io badge
  README.md
Labels: documentation

#6 Add license file
  LICENSE
Labels: documentation

#5 Migrate old project files to the new 2017 format
  .editorconfig
  .gitignore
  Hardcodet.NotifyIcon.Wpf/Source/Directory.Build.props
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf.sln
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/NotifyIconWpf.csproj
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Sample Project.csproj
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/Windowless Sample.csproj
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/Properties/Settings.Designer.cs
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/WindowsFormsSample.csproj
  Hardcodet.NotifyIcon.Wpf/Source/global.json
Labels: enhancement

#8 Code modernising
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/AppBarInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/BalloonFlags.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/NotifyIconData.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/SystemInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/TrayInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/WinApi.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/WindowClass.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/WindowMessageSink.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/RoutedEventHelper.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/TaskbarIcon.Declarations.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/TaskbarIcon.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Util.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/App.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Commands/CommandBase.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Main.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Showcase/FancyBalloon.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Showcase/FancyPopup.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Showcase/FancyToolTip.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Showcase/WelcomeBalloon.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/02 - ToolTips/InlineToolTipWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/02 - ToolTips/SimpleUserControl.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/02 - ToolTips/UserControlToolTipWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/03 - Popups/InlinePopupWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/04 - ContextMenus/InlineContextMenuWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/05 - Balloons/BalloonSampleWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/06 - Commands/CommandWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Sample Project/Tutorials/09 - MVVM/ClockPopup.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/DelegateCommand.cs
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/MainWindow.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/NotifyIconViewModel.cs
  Hardcodet.NotifyIcon.Wpf/Source/Windowless Sample/Properties/AssemblyInfo.cs
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/FancyPopup.xaml.cs
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/Program.cs
  Hardcodet.NotifyIcon.Wpf/Source/WindowsFormsSample/Properties/AssemblyInfo.cs
Labels: Refactoring

#10 Removing some of the "magic numbers"
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/NotifyIconVersion.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/WindowMessageSink.cs
  Hardcodet.NotifyIcon.Wpf/Source/NotifyIconWpf/Interop/WindowsMessages.cs
Labels: Refactoring
