Repository hardcodet/wpf-notifyicon, pull requests merged in 2024-10, with the labels that each got.

#87 ContextMenu is fired twice and ends up never showing up
  src/NotifyIconWpf/TaskbarIcon.cs
Labels: Fix

#114 Improve icon selection to pick the best-fitting icon size from ICO files
  src/NotifyIconWpf/Interop/SystemInfo.cs
  src/NotifyIconWpf/Util.cs
Labels: Fix

#115 Add support for different types of ImageSource
  src/NotifyIconWpf/IconExtensions.cs
  src/NotifyIconWpf/TaskbarIcon.Declarations.cs
  src/NotifyIconWpf/Util.cs
Labels: Enhancement, Fix

#117 Fix trayicon theme change
  src/NotifyIconWpf.Sample.ShowCases/Commands/CloseWindowCommand.cs
  src/NotifyIconWpf.Sample.ShowCases/Tutorials/03 - Popups/InlinePopupWindow.xaml
  src/NotifyIconWpf/TaskbarIcon.cs
Labels: Fix

#118 Add BalloonClosed event for custom balloon
  src/NotifyIconWpf/TaskbarIcon.Declarations.cs
  src/NotifyIconWpf/TaskbarIcon.cs
Labels: Enhancement

#120 Fix double execution of LeftClickCommand
  src/NotifyIconWpf/Interop/WindowMessageSink.cs
Labels: Fix
